# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en

timezone: Africa/Nairobi

# ↓ --------------------------
# jekyll-seo-tag settings

title: Ongalo Glenn

tagline: "SOC Analyst | Threat Detection & Incident Response"

description: >-
  SOC Analyst based in Nairobi, Kenya. Skilled in threat detection,
  log analysis, network enumeration, and incident response. Actively
  training on Hack The Box Academy and building hands-on lab experience.

url: "https://glenn456.github.io"

github:
  username: glenn456

twitter:
  username: OngaloGlenn2167

social:
  name: Ongalo Glenn
  email: ongaloglenn45@gmail.com
  links:
    - https://x.com/OngaloGlen18297
    - https://github.com/glenn456
    - https://www.linkedin.com/in/ongalo-glenn

# ↑ --------------------------

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode: dark

cdn:

avatar: assets/img/Ongalo.jpg # add your photo path here once uploaded e.g. assets/img/ongalo.jpg

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

baseurl: ""

# ------------ Do not modify below ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
